openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Clients API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: Clients
  description: ClientController API /clients
paths:
  /clients/:
    get:
      tags:
      - Clients
      operationId: ListClients
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      - name: client_group_id
        in: query
        description: client group id
        required: false
        x-exportParamName: ClientGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientsResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List clients
      x-summary-source: derived
  /clients/{client_id}:
    get:
      tags:
      - Clients
      operationId: GetClient
      parameters:
      - name: client_id
        in: path
        description: client id
        required: true
        x-exportParamName: ClientId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get client
      x-summary-source: derived
components:
  schemas:
    ClientResp:
      type: object
      required:
      - client
      properties:
        client:
          $ref: '#/components/schemas/Client'
      title: ClientResp
      example:
        client:
          code: code
          client_group:
            name: name
            id: 5
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 5
          status: status
    Client:
      type: object
      properties:
        client_group:
          $ref: '#/components/schemas/ClientGroup_Nestview'
        code:
          type: string
        create:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        status:
          type: string
        update:
          type: string
          format: date-time
      title: Client
      example:
        code: code
        client_group:
          name: name
          id: 5
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 5
        status: status
    ClientsResp:
      type: object
      required:
      - clients
      properties:
        clients:
          type: array
          items:
            $ref: '#/components/schemas/Client'
      title: ClientsResp
      example:
        clients:
        - code: code
          client_group:
            name: name
            id: 5
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 5
          status: status
        - code: code
          client_group:
            name: name
            id: 5
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 5
          status: status
    ClientGroup_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: ClientGroup_Nestview
      example:
        name: name
        id: 5
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
