openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Os Zone Translogs API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: os-zone-translogs
  description: OSZoneTranslogController API /os-zone-translogs
paths:
  /os-zone-translogs/:
    get:
      tags:
      - os-zone-translogs
      description: List os zone translogs
      operationId: ListOSZoneTranslogs
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: epoch_uuid
        in: query
        description: paging param
        required: false
        x-exportParamName: EpochUuid
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSZoneTranslogsResp'
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List OS zone translogs
      x-summary-source: derived
  /os-zone-translogs/{translog_uuid}:
    get:
      tags:
      - os-zone-translogs
      description: Get a os zone translog
      operationId: GetOSZoneTranslog
      parameters:
      - name: translog_uuid
        in: path
        description: translog uuid
        required: true
        x-exportParamName: TranslogUuid
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSZoneTranslogResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get OS zone translog
      x-summary-source: derived
components:
  schemas:
    OSZoneTranslogsResp:
      type: object
      properties:
        os_zone_translogs:
          type: array
          items:
            $ref: '#/components/schemas/OSZoneTranslog'
      title: OSZoneTranslogsResp
      example:
        os_zone_translogs:
        - resource_type: resource_type
          resource_uuid: resource_uuid
          action: action
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          uuid: uuid
        - resource_type: resource_type
          resource_uuid: resource_uuid
          action: action
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          uuid: uuid
    OSZoneTranslog:
      type: object
      properties:
        action:
          type: string
        create:
          type: string
          format: date-time
        resource_type:
          type: string
        resource_uuid:
          type: string
        update:
          type: string
          format: date-time
        uuid:
          type: string
      title: OSZoneTranslog
      description: OSZoneTranslog defines model of os zone translog.
      example:
        resource_type: resource_type
        resource_uuid: resource_uuid
        action: action
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        uuid: uuid
    OSZoneTranslogResp:
      type: object
      properties:
        os_zone_translog:
          $ref: '#/components/schemas/OSZoneTranslog'
      title: OSZoneTranslogResp
      example:
        os_zone_translog:
          resource_type: resource_type
          resource_uuid: resource_uuid
          action: action
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          uuid: uuid
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
