openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Mapping Groups API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: mapping-groups
  description: MappingGroupController Operations able mapping groups
paths:
  /mapping-groups/:
    get:
      tags:
      - mapping-groups
      operationId: ListMappingGroups
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: access_path_id
        in: query
        description: access path id
        required: false
        x-exportParamName: AccessPathId
        schema:
          type: integer
          format: int64
      - name: client_group_id
        in: query
        description: client group id
        required: false
        x-exportParamName: ClientGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupsResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List mapping groups
      x-summary-source: derived
    post:
      tags:
      - mapping-groups
      description: create a mapping group in access path
      operationId: CreateMappingGroup
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MappingGroupCreateReq'
        description: mapping info
        required: true
      summary: Create mapping group
      x-summary-source: derived
  /mapping-groups/{mapping_group_id}:
    get:
      tags:
      - mapping-groups
      description: Get mapping group by id
      operationId: GetMappingGroup
      parameters:
      - name: mapping_group_id
        in: path
        description: mapping group id
        required: true
        x-exportParamName: MappingGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get mapping group
      x-summary-source: derived
    delete:
      tags:
      - mapping-groups
      operationId: DeleteMappingGroup
      parameters:
      - name: mapping_group_id
        in: path
        description: mapping group id
        required: true
        x-exportParamName: MappingGroupId
        schema:
          type: integer
          format: int64
      - name: force
        in: query
        description: force delete or not
        required: false
        x-exportParamName: Force
        schema:
          type: boolean
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete mapping group
      x-summary-source: derived
    patch:
      tags:
      - mapping-groups
      description: update mapping group
      operationId: UpdateMappingGroup
      parameters:
      - name: mapping_group_id
        in: path
        description: mapping group id
        required: true
        x-exportParamName: MappingGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MappingGroupUpdateReq'
        description: mapping info
        required: true
      summary: Update mapping group
      x-summary-source: derived
  /mapping-groups/{mapping_group_id}/block-volumes:
    post:
      tags:
      - mapping-groups
      description: add volumes to mapping group
      operationId: AddVolumes
      parameters:
      - name: mapping_group_id
        in: path
        description: mapping group id
        required: true
        x-exportParamName: MappingGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MappingGroupAddVolumesReq'
        description: block volume ids
        required: true
      summary: Add volumes
      x-summary-source: derived
    delete:
      tags:
      - mapping-groups
      description: remove volumes from mapping group
      operationId: RemoveVolumes
      parameters:
      - name: mapping_group_id
        in: path
        description: mapping group id
        required: true
        x-exportParamName: MappingGroupId
        schema:
          type: integer
          format: int64
      - name: force
        in: query
        description: force delete or not
        required: false
        x-exportParamName: Force
        schema:
          type: boolean
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MappingGroupRemoveVolumesReq'
        description: block volume ids
        required: true
      summary: Remove volumes
      x-summary-source: derived
  /mapping-groups/{mapping_group_id}/client-group:
    patch:
      tags:
      - mapping-groups
      description: update client group in mapping group
      operationId: UpdateMappingGroupClientGroup
      parameters:
      - name: mapping_group_id
        in: path
        description: mapping group id
        required: true
        x-exportParamName: MappingGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingGroupResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MappingGroupUpdateClientGroupReq'
        description: client group id
        required: true
      summary: Update mapping group client group
      x-summary-source: derived
components:
  schemas:
    MappingGroupCreateReq:
      type: object
      required:
      - mapping_group
      properties:
        mapping_group:
          $ref: '#/components/schemas/MappingGroupReq'
      title: MappingGroupCreateReq
      example:
        mapping_group:
          client_group_id: 5
          block_volume_ids:
          - 1
          - 1
          access_path_id: 6
    MappingGroupRemoveVolumesReq:
      type: object
      required:
      - block_volume_ids
      properties:
        block_volume_ids:
          type: array
          items:
            type: integer
            format: int64
      title: MappingGroupRemoveVolumesReq
      example:
        block_volume_ids:
        - 0
        - 0
    MappingGroupUpdateClientGroupReq:
      type: object
      required:
      - client_group_id
      properties:
        client_group_id:
          type: integer
          format: int64
      title: MappingGroupUpdateClientGroupReq
      example:
        client_group_id: 0
    MappingGroupResp:
      type: object
      required:
      - mapping_group
      properties:
        mapping_group:
          $ref: '#/components/schemas/MappingGroup'
      title: MappingGroupResp
      example:
        mapping_group:
          client_group:
            name: name
            id: 5
          access_path:
            name: name
            id: 0
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 6
          status: status
    MappingGroupUpdateReq:
      type: object
      required:
      - mapping_group
      properties:
        mapping_group:
          $ref: '#/components/schemas/MappingGroupUpdateReq_MappingGroup'
      title: MappingGroupUpdateReq
      example:
        mapping_group:
          block_volume_ids:
          - 0
          - 0
    AccessPath_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: AccessPath_Nestview
      example:
        name: name
        id: 0
    MappingGroupsResp:
      type: object
      required:
      - mapping_groups
      properties:
        mapping_groups:
          type: array
          items:
            $ref: '#/components/schemas/MappingGroup'
      title: MappingGroupsResp
      example:
        mapping_groups:
        - client_group:
            name: name
            id: 5
          access_path:
            name: name
            id: 0
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 6
          status: status
        - client_group:
            name: name
            id: 5
          access_path:
            name: name
            id: 0
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 6
          status: status
    MappingGroup:
      type: object
      properties:
        access_path:
          $ref: '#/components/schemas/AccessPath_Nestview'
        client_group:
          $ref: '#/components/schemas/ClientGroup_Nestview'
        create:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        status:
          type: string
        update:
          type: string
          format: date-time
      title: MappingGroup
      description: MappingGroup defines the mapping group of volumes and client groups
      example:
        client_group:
          name: name
          id: 5
        access_path:
          name: name
          id: 0
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 6
        status: status
    MappingGroupAddVolumesReq:
      type: object
      required:
      - block_volume_ids
      properties:
        block_volume_ids:
          type: array
          items:
            type: integer
            format: int64
      title: MappingGroupAddVolumesReq
      example:
        block_volume_ids:
        - 0
        - 0
    MappingGroupUpdateReq_MappingGroup:
      type: object
      properties:
        block_volume_ids:
          type: array
          items:
            type: integer
            format: int64
      title: MappingGroupUpdateReq_MappingGroup
      example:
        block_volume_ids:
        - 0
        - 0
    MappingGroupReq:
      type: object
      properties:
        access_path_id:
          type: integer
          format: int64
        block_volume_ids:
          type: array
          items:
            type: integer
            format: int64
        client_group_id:
          type: integer
          format: int64
      title: MappingGroupReq
      example:
        client_group_id: 5
        block_volume_ids:
        - 1
        - 1
        access_path_id: 6
    ClientGroup_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: ClientGroup_Nestview
      example:
        name: name
        id: 5
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
