openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Users API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: Users
  description: UserController Manage users
paths:
  /users/:
    get:
      tags:
      - Users
      operationId: ListUsers
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: name
        in: query
        description: user name
        required: false
        x-exportParamName: Name
        schema:
          type: string
      - name: email
        in: query
        description: user email
        required: false
        x-exportParamName: Email
        schema:
          type: string
      - name: all
        in: query
        description: show all users
        required: false
        x-exportParamName: All
        schema:
          type: boolean
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List users
      x-summary-source: derived
    post:
      tags:
      - Users
      description: create user
      operationId: CreateUser
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateReq'
        description: user info
        required: true
      summary: Create user
      x-summary-source: derived
  /users/{user_id}:
    get:
      tags:
      - Users
      description: get a user
      operationId: GetUser
      parameters:
      - name: user_id
        in: path
        description: user id
        required: true
        x-exportParamName: UserId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get user
      x-summary-source: derived
    delete:
      tags:
      - Users
      description: delete user
      operationId: DeleteUser
      parameters:
      - name: user_id
        in: path
        description: user id
        required: true
        x-exportParamName: UserId
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: No Content
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete user
      x-summary-source: derived
    patch:
      tags:
      - Users
      description: update user info
      operationId: UpdateUser
      parameters:
      - name: user_id
        in: path
        description: user id
        required: true
        x-exportParamName: UserId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateReq'
        description: user info
        required: true
      summary: Update user
      x-summary-source: derived
  /users/{user_id}/password:
    put:
      tags:
      - Users
      description: change user password
      operationId: ChangePassword
      parameters:
      - name: user_id
        in: path
        description: user id
        required: true
        x-exportParamName: UserId
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: No Content
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordReq'
        description: update info
        required: true
      summary: Change password
      x-summary-source: derived
  /users/{user_id}/settings:
    get:
      tags:
      - Users
      description: update user info
      operationId: GetUserSettings
      parameters:
      - name: user_id
        in: path
        description: user id
        required: true
        x-exportParamName: UserId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'
        400:
          description: BadRequest
        403:
          description: Forbidden
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get user settings
      x-summary-source: derived
    patch:
      tags:
      - Users
      description: update user info
      operationId: UpdateUserSettings
      parameters:
      - name: user_id
        in: path
        description: user id
        required: true
        x-exportParamName: UserId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'
        400:
          description: BadRequest
        403:
          description: Forbidden
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSettings'
        description: user settings
        required: true
      summary: Update user settings
      x-summary-source: derived
components:
  schemas:
    UserUpdateReq:
      type: object
      required:
      - user
      properties:
        user:
          $ref: '#/components/schemas/UserUpdateReq_User'
      title: UserUpdateReq
      example:
        user:
          roles:
          - roles
          - roles
          name: name
          email: email
          enabled: true
    ChangePasswordReq:
      type: object
      required:
      - user
      properties:
        user:
          description: user
          $ref: '#/components/schemas/ChangePasswordReq_Req'
      title: ChangePasswordReq
      example:
        user:
          original_password: original_password
          password: password
          rsa_key_id: rsa_key_id
          encrypted_original_password: encrypted_original_password
          encrypted_password: encrypted_password
    UserCreateReq:
      type: object
      required:
      - user
      properties:
        user:
          $ref: '#/components/schemas/UserCreateReq_User'
      title: UserCreateReq
      example:
        user:
          password: password
          roles:
          - roles
          - roles
          name: name
          email: email
          enabled: true
    UserCreateReq_User:
      type: object
      required:
      - email
      - enabled
      - name
      - password
      properties:
        email:
          type: string
          description: email of user
        enabled:
          type: boolean
          description: enable or disable the user
        name:
          type: string
          description: name of user
        password:
          type: string
          description: password of user
        roles:
          type: array
          description: roles of user
          items:
            type: string
      title: UserCreateReq_User
      example:
        password: password
        roles:
        - roles
        - roles
        name: name
        email: email
        enabled: true
    ChangePasswordReq_Req:
      type: object
      required:
      - original_password
      - password
      properties:
        encrypted_original_password:
          type: string
          description: encrypted original password for auth
        encrypted_password:
          type: string
          description: encrypted password for auth
        original_password:
          type: string
          description: original password of user
        password:
          type: string
          description: new password of user
        rsa_key_id:
          type: string
          description: rsa key id
      title: ChangePasswordReq_Req
      example:
        original_password: original_password
        password: password
        rsa_key_id: rsa_key_id
        encrypted_original_password: encrypted_original_password
        encrypted_password: encrypted_password
    IdentityPlatform_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: id of identity platform
        name:
          type: string
          description: name of identity platform
      title: IdentityPlatform_Nestview
      example:
        name: name
        id: 6
    UserRecord:
      title: UserRecord
      allOf:
      - $ref: '#/components/schemas/User'
      description: UserRecord defines user record for api response
    UserResp:
      type: object
      required:
      - user
      properties:
        user:
          description: user
          $ref: '#/components/schemas/UserRecord'
      title: UserResp
      example:
        user: ''
    User:
      type: object
      properties:
        create:
          type: string
          format: date-time
          description: time of creating user
        email:
          type: string
          description: email of user
        enabled:
          type: boolean
          description: enable the user or not
        external_id:
          type: string
          description: external id of user
        id:
          type: integer
          format: int64
          description: id of user
        identity_platform:
          description: identity platform of user
          $ref: '#/components/schemas/IdentityPlatform_Nestview'
        name:
          type: string
          description: name of user
        password_last_update:
          type: string
          format: date-time
          description: time of last password update
        roles:
          type: array
          description: roles of user
          items:
            type: string
      title: User
    UserSettings:
      type: object
      required:
      - user
      properties:
        user:
          $ref: '#/components/schemas/UserSettings_User'
      title: UserSettings
      example:
        user:
          settings:
            dashboard: dashboard
    UsersResp:
      type: object
      required:
      - users
      properties:
        users:
          type: array
          description: users
          items:
            $ref: '#/components/schemas/UserRecord'
      title: UsersResp
      example:
        users:
        - ''
        - ''
    UserSettings_User_Settings:
      type: object
      properties:
        dashboard:
          type: string
          description: dashboard setting
      title: UserSettings_User_Settings
      example:
        dashboard: dashboard
    UserUpdateReq_User:
      type: object
      required:
      - email
      - enabled
      - name
      properties:
        email:
          type: string
          description: email of user
        enabled:
          type: boolean
          description: enable or disable the user
        name:
          type: string
          description: name of user
        roles:
          type: array
          description: roles of user
          items:
            type: string
      title: UserUpdateReq_User
      example:
        roles:
        - roles
        - roles
        name: name
        email: email
        enabled: true
    UserSettings_User:
      type: object
      required:
      - settings
      properties:
        settings:
          $ref: '#/components/schemas/UserSettings_User_Settings'
      title: UserSettings_User
      example:
        settings:
          dashboard: dashboard
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
