openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Dp Fs Snapshot Policies API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: dp-fs-snapshot-policies
  description: DpFSSnapshotPolicyController API /dp-fs-snapshot-policies
paths:
  /dp-fs-snapshot-policies/:
    get:
      tags:
      - dp-fs-snapshot-policies
      description: List dp fs snapshot policies
      operationId: ListDpFSSnapshotPolicies
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpFSSnapshotPoliciesResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List dp FS snapshot policies
      x-summary-source: derived
    post:
      tags:
      - dp-fs-snapshot-policies
      description: Create dp fs snapshot policy
      operationId: CreateDpFSSnapshotPolicy
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpFSSnapshotPolicyResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DpFSSnapshotPolicyCreateReq'
        description: policy info
        required: true
      summary: Create dp FS snapshot policy
      x-summary-source: derived
  /dp-fs-snapshot-policies/{policy_id}:
    get:
      tags:
      - dp-fs-snapshot-policies
      description: Get dp fs snapshot policy
      operationId: GetDpFSSnapshotPolicy
      parameters:
      - name: policy_id
        in: path
        description: resource id
        required: true
        x-exportParamName: PolicyId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpFSSnapshotPolicyResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get dp FS snapshot policy
      x-summary-source: derived
    delete:
      tags:
      - dp-fs-snapshot-policies
      description: Delete dp fs snapshot policy
      operationId: DeleteDpFSSnapshotPolicy
      parameters:
      - name: policy_id
        in: path
        description: resource id
        required: true
        x-exportParamName: PolicyId
        schema:
          type: integer
          format: int64
      - name: force
        in: query
        description: force delete or not
        required: false
        x-exportParamName: Force
        schema:
          type: boolean
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpFSSnapshotPolicyResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete dp FS snapshot policy
      x-summary-source: derived
    patch:
      tags:
      - dp-fs-snapshot-policies
      description: Update dp fs snapshot policy
      operationId: UpdateDpFSSnapshotPolicy
      parameters:
      - name: policy_id
        in: path
        description: resource id
        required: true
        x-exportParamName: PolicyId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpFSSnapshotPolicyResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DpFSSnapshotPolicyUpdateReq'
        description: policy info
        required: true
      summary: Update dp FS snapshot policy
      x-summary-source: derived
components:
  schemas:
    DpFSSnapshotPolicyCreateReq_Policy:
      type: object
      required:
      - cron_expr
      - dp_gateway_id
      - name
      - retained_max
      properties:
        cron_expr:
          type: string
        dp_gateway_id:
          type: integer
          format: int64
        name:
          type: string
        retained_max:
          type: integer
          format: int64
      title: DpFSSnapshotPolicyCreateReq_Policy
    DpFSSnapshotPolicy:
      type: object
      properties:
        create:
          type: string
          format: date-time
        cron_expr:
          type: string
        dp_gateway:
          $ref: '#/components/schemas/DpGateway_Nestview'
        fs_folder_num:
          type: integer
          format: int64
        id:
          type: integer
          format: int64
        name:
          type: string
        retained_max:
          type: integer
          format: int64
        status:
          type: string
        update:
          type: string
          format: date-time
      title: DpFSSnapshotPolicy
      description: DpFSSnapshotPolicy protects a fs folder by snapshot
      example:
        retained_max: 1
        cron_expr: cron_expr
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        dp_gateway:
          name: name
          id: 6
        id: 6
        fs_folder_num: 0
        status: status
    DpFSSnapshotPolicyResp:
      type: object
      properties:
        dp_fs_snapshot_policy:
          $ref: '#/components/schemas/DpFSSnapshotPolicy'
      title: DpFSSnapshotPolicyResp
      example:
        dp_fs_snapshot_policy:
          retained_max: 1
          cron_expr: cron_expr
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          dp_gateway:
            name: name
            id: 6
          id: 6
          fs_folder_num: 0
          status: status
    DpFSSnapshotPolicyCreateReq:
      type: object
      required:
      - dp_fs_snapshot_policy
      properties:
        dp_fs_snapshot_policy:
          $ref: '#/components/schemas/DpFSSnapshotPolicyCreateReq_Policy'
      title: DpFSSnapshotPolicyCreateReq
    DpFSSnapshotPolicyUpdateReq:
      type: object
      required:
      - dp_fs_snapshot_policy
      properties:
        dp_fs_snapshot_policy:
          $ref: '#/components/schemas/DpFSSnapshotPolicyUpdateReq_Policy'
      title: DpFSSnapshotPolicyUpdateReq
    DpFSSnapshotPolicyUpdateReq_Policy:
      type: object
      properties:
        cron_expr:
          type: string
        name:
          type: string
        retained_max:
          type: integer
          format: int64
      title: DpFSSnapshotPolicyUpdateReq_Policy
    DpFSSnapshotPoliciesResp:
      type: object
      properties:
        dp_fs_snapshot_policies:
          type: array
          items:
            $ref: '#/components/schemas/DpFSSnapshotPolicy'
      title: DpFSSnapshotPoliciesResp
      example:
        dp_fs_snapshot_policies:
        - retained_max: 1
          cron_expr: cron_expr
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          dp_gateway:
            name: name
            id: 6
          id: 6
          fs_folder_num: 0
          status: status
        - retained_max: 1
          cron_expr: cron_expr
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          dp_gateway:
            name: name
            id: 6
          id: 6
          fs_folder_num: 0
          status: status
    DpGateway_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: DpGateway_Nestview
      example:
        name: name
        id: 6
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
