openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Dp Gateways API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: dp-gateways
  description: DpGatewayController API /dp-gateways/
paths:
  /dp-gateways/:
    get:
      tags:
      - dp-gateways
      operationId: ListDpGateways
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpGatewaysResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List dp gateways
      x-summary-source: derived
    post:
      tags:
      - dp-gateways
      description: Create a dp gateway
      operationId: CreateDpGateway
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpGatewayResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DpGatewayCreateReq'
        description: dp gateway info
        required: true
      summary: Create dp gateway
      x-summary-source: derived
  /dp-gateways/{gateway_id}:
    get:
      tags:
      - dp-gateways
      operationId: GetDpGateway
      parameters:
      - name: gateway_id
        in: path
        description: dp gateway id
        required: true
        x-exportParamName: GatewayId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpGatewayResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get dp gateway
      x-summary-source: derived
    delete:
      tags:
      - dp-gateways
      operationId: DeleteDpGateway
      parameters:
      - name: gateway_id
        in: path
        description: dp gateway id
        required: true
        x-exportParamName: GatewayId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpGatewayResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete dp gateway
      x-summary-source: derived
    patch:
      tags:
      - dp-gateways
      description: Update a dp gateway
      operationId: UpdateDpGateway
      parameters:
      - name: gateway_id
        in: path
        description: dp gateway id
        required: true
        x-exportParamName: GatewayId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpGatewayResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DpGatewayUpdateReq'
        description: dp gateway info
        required: true
      summary: Update dp gateway
      x-summary-source: derived
components:
  schemas:
    DpGatewayUpdateReq_Gateway:
      type: object
      required:
      - name
      properties:
        name:
          type: string
          description: dp gateway name
      title: DpGatewayUpdateReq_Gateway
      example:
        name: name
    DpGatewaysResp:
      type: object
      required:
      - dp_gateways
      properties:
        dp_gateways:
          type: array
          description: dp gateways
          items:
            $ref: '#/components/schemas/DpGateway'
      title: DpGatewaysResp
      example:
        dp_gateways:
        - admin_port: 0
          gateway_port: 6
          host:
            name: name
            admin_ip: admin_ip
            id: 0
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 1
          status: status
        - admin_port: 0
          gateway_port: 6
          host:
            name: name
            admin_ip: admin_ip
            id: 0
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 1
          status: status
    DpGatewayCreateReq:
      type: object
      properties:
        dp_gateway:
          $ref: '#/components/schemas/DpGatewayCreateReq_Gateway'
      title: DpGatewayCreateReq
      example:
        dp_gateway:
          name: name
          host_id: 0
    DpGatewayCreateReq_Gateway:
      type: object
      required:
      - host_id
      - name
      properties:
        host_id:
          type: integer
          format: int64
        name:
          type: string
      title: DpGatewayCreateReq_Gateway
      example:
        name: name
        host_id: 0
    DpGatewayUpdateReq:
      type: object
      properties:
        dp_gateway:
          $ref: '#/components/schemas/DpGatewayUpdateReq_Gateway'
      title: DpGatewayUpdateReq
      example:
        dp_gateway:
          name: name
    Host_Nestview:
      type: object
      required:
      - admin_ip
      properties:
        admin_ip:
          type: string
        id:
          type: integer
          format: int64
        name:
          type: string
      title: Host_Nestview
      example:
        name: name
        admin_ip: admin_ip
        id: 0
    DpGatewayResp:
      type: object
      required:
      - dp_gateway
      properties:
        dp_gateway:
          description: dp gateway
          $ref: '#/components/schemas/DpGateway'
      title: DpGatewayResp
      example:
        dp_gateway:
          admin_port: 0
          gateway_port: 6
          host:
            name: name
            admin_ip: admin_ip
            id: 0
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 1
          status: status
    DpGateway:
      type: object
      properties:
        admin_port:
          type: integer
          format: int64
        create:
          type: string
          format: date-time
        gateway_port:
          type: integer
          format: int64
        host:
          $ref: '#/components/schemas/Host_Nestview'
        id:
          type: integer
          format: int64
        name:
          type: string
        status:
          type: string
        update:
          type: string
          format: date-time
      title: DpGateway
      description: DpGateway is a process to execute data protection jobs
      example:
        admin_port: 0
        gateway_port: 6
        host:
          name: name
          admin_ip: admin_ip
          id: 0
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 1
        status: status
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
