openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS S3 Load Balancers API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: s3-load-balancers
  description: S3LoadBalancerController API
paths:
  /s3-load-balancers/:
    get:
      tags:
      - s3-load-balancers
      description: List s3 load balancers
      operationId: ListS3LoadBalancers
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      - name: group_id
        in: query
        description: s3 load balancer group id
        required: false
        x-exportParamName: GroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/S3LoadBalancersResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List S3 load balancers
      x-summary-source: derived
  /s3-load-balancers/samples:
    get:
      tags:
      - s3-load-balancers
      description: Get samples of multiple s3 load balancers
      operationId: BatchGetS3LoadBalancerSamples
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultiS3LoadBalancersSamplesResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Batch get S3 load balancer samples
      x-summary-source: derived
  /s3-load-balancers/{load_balancer_id}:
    get:
      tags:
      - s3-load-balancers
      description: Get s3 load balancer
      operationId: GetS3LoadBalancer
      parameters:
      - name: load_balancer_id
        in: path
        description: s3 load balancer id
        required: true
        x-exportParamName: LoadBalancerId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/S3LoadBalancerResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      summary: Get S3 load balancer
      x-summary-source: derived
  /s3-load-balancers/{s3_load_balancer_id}/samples:
    get:
      tags:
      - s3-load-balancers
      description: get a s3 load balancer's samples
      operationId: GetS3LoadBalancerSamples
      parameters:
      - name: s3_load_balancer_id
        in: path
        description: s3 load balancer id
        required: true
        x-exportParamName: S3LoadBalancerId
        schema:
          type: integer
          format: int64
      - name: duration_begin
        in: query
        description: duration begin timestamp
        required: false
        x-exportParamName: DurationBegin
        schema:
          type: string
      - name: duration_end
        in: query
        description: duration end timestamp
        required: false
        x-exportParamName: DurationEnd
        schema:
          type: string
      - name: period
        in: query
        description: samples period
        required: false
        x-exportParamName: Period
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/S3LoadBalancerSamplesResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get S3 load balancer samples
      x-summary-source: derived
components:
  schemas:
    SSLCertificate_Nestview:
      type: object
      properties:
        force_https:
          type: boolean
          description: redirect http request to https
        id:
          type: integer
          format: int64
          description: certificate id
        name:
          type: string
          description: certificate name
      title: SSLCertificate_Nestview
      example:
        force_https: true
        name: name
        id: 2
    S3LoadBalancerGroup_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        status:
          type: string
      title: S3LoadBalancerGroup_Nestview
      example:
        name: name
        id: 6
        status: status
    S3LoadBalancerStat:
      type: object
      properties:
        active_connections:
          type: number
          format: double
        cpu_util:
          type: number
          format: double
        create:
          type: string
          format: date-time
        down_bandwidth_kbyte:
          type: number
          format: double
        failure_requests:
          type: number
          format: double
        mem_usage_percent:
          type: number
          format: double
        success_requests:
          type: number
          format: double
        up_bandwidth_kbyte:
          type: number
          format: double
      title: S3LoadBalancerStat
      description: S3LoadBalancerStat define s3 load balancer stat info
      example:
        up_bandwidth_kbyte: 9.301444243932576
        down_bandwidth_kbyte: 5.962133916683182
        success_requests: 7.061401241503109
        mem_usage_percent: 2.3021358869347655
        create: '2000-01-23T04:56:07.000+00:00'
        active_connections: 6.027456183070403
        cpu_util: 1.4658129805029452
        failure_requests: 5.637376656633329
    Paging:
      type: object
      properties:
        count:
          type: integer
          format: int64
        duration:
          type: integer
          format: int64
        duration_begin:
          type: string
          format: date-time
        duration_end:
          type: string
          format: date-time
        limit:
          type: integer
          format: int64
        next:
          type: string
        offset:
          type: integer
          format: int64
        period:
          type: string
        total_count:
          type: integer
          format: int64
        truncated:
          type: boolean
      title: Paging
      description: Paging defines paging object
      example:
        duration: 1
        next: next
        period: period
        offset: 5
        total_count: 2
        count: 6
        duration_end: '2000-01-23T04:56:07.000+00:00'
        limit: 5
        truncated: true
        duration_begin: '2000-01-23T04:56:07.000+00:00'
    S3LoadBalancer:
      type: object
      properties:
        create:
          type: string
          format: date-time
        description:
          type: string
        group:
          $ref: '#/components/schemas/S3LoadBalancerGroup_Nestview'
        host:
          $ref: '#/components/schemas/Host_Nestview'
        https_port:
          type: integer
          format: int64
        id:
          type: integer
          format: int64
        interface_name:
          type: string
          description: the interface where vip is bound, exclusive to ip
        ip:
          type: string
          description: the interface of ip where vip is bound, exclusive to interface_name
        name:
          type: string
        port:
          type: integer
          format: int64
        roles:
          type: array
          items:
            type: string
        search_https_port:
          type: integer
          format: int64
        search_port:
          type: integer
          format: int64
        ssl_certificate:
          $ref: '#/components/schemas/SSLCertificate_Nestview'
        status:
          type: string
        sync_port:
          type: integer
          format: int64
        update:
          type: string
          format: date-time
        vip:
          type: string
          description: designated(master) vip
        vip_mask:
          type: integer
          format: int64
          description: 'mask of vip, default: 32'
        vips:
          type: string
          description: current effective vips
        web_console_endpoint:
          type: string
      title: S3LoadBalancer
      description: S3LoadBalancer is a load balancer for rados loadBalancers @grpc-models-proto
    S3LoadBalancerSamplesResp:
      type: object
      required:
      - s3_load_balancer_samples
      properties:
        s3_load_balancer_samples:
          type: array
          description: s3 load balancer samples
          items:
            $ref: '#/components/schemas/S3LoadBalancerStat'
      title: S3LoadBalancerSamplesResp
      example:
        s3_load_balancer_samples:
        - up_bandwidth_kbyte: 9.301444243932576
          down_bandwidth_kbyte: 5.962133916683182
          success_requests: 7.061401241503109
          mem_usage_percent: 2.3021358869347655
          create: '2000-01-23T04:56:07.000+00:00'
          active_connections: 6.027456183070403
          cpu_util: 1.4658129805029452
          failure_requests: 5.637376656633329
        - up_bandwidth_kbyte: 9.301444243932576
          down_bandwidth_kbyte: 5.962133916683182
          success_requests: 7.061401241503109
          mem_usage_percent: 2.3021358869347655
          create: '2000-01-23T04:56:07.000+00:00'
          active_connections: 6.027456183070403
          cpu_util: 1.4658129805029452
          failure_requests: 5.637376656633329
    MultiS3LoadBalancersSamplesResp:
      type: object
      properties:
        s3_load_balancers_samples:
          type: array
          items:
            $ref: '#/components/schemas/S3LoadBalancerSamplesElem'
      title: MultiS3LoadBalancersSamplesResp
      example:
        s3_load_balancers_samples:
        - paging:
            duration: 1
            next: next
            period: period
            offset: 5
            total_count: 2
            count: 6
            duration_end: '2000-01-23T04:56:07.000+00:00'
            limit: 5
            truncated: true
            duration_begin: '2000-01-23T04:56:07.000+00:00'
          id: 0
          samples:
          - up_bandwidth_kbyte: 9.301444243932576
            down_bandwidth_kbyte: 5.962133916683182
            success_requests: 7.061401241503109
            mem_usage_percent: 2.3021358869347655
            create: '2000-01-23T04:56:07.000+00:00'
            active_connections: 6.027456183070403
            cpu_util: 1.4658129805029452
            failure_requests: 5.637376656633329
          - up_bandwidth_kbyte: 9.301444243932576
            down_bandwidth_kbyte: 5.962133916683182
            success_requests: 7.061401241503109
            mem_usage_percent: 2.3021358869347655
            create: '2000-01-23T04:56:07.000+00:00'
            active_connections: 6.027456183070403
            cpu_util: 1.4658129805029452
            failure_requests: 5.637376656633329
        - paging:
            duration: 1
            next: next
            period: period
            offset: 5
            total_count: 2
            count: 6
            duration_end: '2000-01-23T04:56:07.000+00:00'
            limit: 5
            truncated: true
            duration_begin: '2000-01-23T04:56:07.000+00:00'
          id: 0
          samples:
          - up_bandwidth_kbyte: 9.301444243932576
            down_bandwidth_kbyte: 5.962133916683182
            success_requests: 7.061401241503109
            mem_usage_percent: 2.3021358869347655
            create: '2000-01-23T04:56:07.000+00:00'
            active_connections: 6.027456183070403
            cpu_util: 1.4658129805029452
            failure_requests: 5.637376656633329
          - up_bandwidth_kbyte: 9.301444243932576
            down_bandwidth_kbyte: 5.962133916683182
            success_requests: 7.061401241503109
            mem_usage_percent: 2.3021358869347655
            create: '2000-01-23T04:56:07.000+00:00'
            active_connections: 6.027456183070403
            cpu_util: 1.4658129805029452
            failure_requests: 5.637376656633329
    S3LoadBalancerSamplesElem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        paging:
          $ref: '#/components/schemas/Paging'
        samples:
          type: array
          items:
            $ref: '#/components/schemas/S3LoadBalancerStat'
      title: S3LoadBalancerSamplesElem
      example:
        paging:
          duration: 1
          next: next
          period: period
          offset: 5
          total_count: 2
          count: 6
          duration_end: '2000-01-23T04:56:07.000+00:00'
          limit: 5
          truncated: true
          duration_begin: '2000-01-23T04:56:07.000+00:00'
        id: 0
        samples:
        - up_bandwidth_kbyte: 9.301444243932576
          down_bandwidth_kbyte: 5.962133916683182
          success_requests: 7.061401241503109
          mem_usage_percent: 2.3021358869347655
          create: '2000-01-23T04:56:07.000+00:00'
          active_connections: 6.027456183070403
          cpu_util: 1.4658129805029452
          failure_requests: 5.637376656633329
        - up_bandwidth_kbyte: 9.301444243932576
          down_bandwidth_kbyte: 5.962133916683182
          success_requests: 7.061401241503109
          mem_usage_percent: 2.3021358869347655
          create: '2000-01-23T04:56:07.000+00:00'
          active_connections: 6.027456183070403
          cpu_util: 1.4658129805029452
          failure_requests: 5.637376656633329
    Host_Nestview:
      type: object
      required:
      - admin_ip
      properties:
        admin_ip:
          type: string
        id:
          type: integer
          format: int64
        name:
          type: string
      title: Host_Nestview
      example:
        name: name
        admin_ip: admin_ip
        id: 0
    S3LoadBalancerRecord:
      title: S3LoadBalancerRecord
      allOf:
      - $ref: '#/components/schemas/S3LoadBalancer'
      - properties:
          samples:
            type: array
            items:
              $ref: '#/components/schemas/S3LoadBalancerStat'
      description: S3LoadBalancerRecord defines s3 load balancer with samples
    S3LoadBalancerResp:
      type: object
      required:
      - s3_load_balancer
      properties:
        s3_load_balancer:
          description: s3 load balancer
          $ref: '#/components/schemas/S3LoadBalancerRecord'
      title: S3LoadBalancerResp
      example:
        s3_load_balancer: ''
    S3LoadBalancersResp:
      type: object
      required:
      - s3_load_balancers
      properties:
        s3_load_balancers:
          type: array
          description: s3 load balancers
          items:
            $ref: '#/components/schemas/S3LoadBalancerRecord'
      title: S3LoadBalancersResp
      example:
        s3_load_balancers:
        - ''
        - ''
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
